version: '2'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongo_data:/data/mongodb/db
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: elasticsearch
    restart: unless-stopped
    volumes:
      - es_data:/data/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:2.4
    container_name: graylog
    restart: unless-stopped
    volumes:
      - graylog_journal:/data/graylog/data/journal
    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=peppersalttabascopiripiri
      - GRAYLOG_ROOT_PASSWORD_SHA2=83319aa4190536f2e404ca8514ab12397da37665c7ad8f0e3439d962871695d2
      - GRAYLOG_WEB_ENDPOINT_URI=http://grayloghost.westus2.cloudapp.azure.com:9000/api
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    links:
      - graylog
    volumes:
      - /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/nginx/ssl:/etc/ssl
  # When you go to the kibana page, it'll ask you for the index pattern. Use `graylog_*`
  kibana:
    image: kibana:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "5601:5601"
    links:
      - elasticsearch

# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local
